name: Build Android APK and Publish to Play Store

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application name'
        required: true
        type: string
      package_id:
        description: 'Android package ID (e.g., com.example.app)'
        required: true
        type: string
      web_app_url:
        description: 'Web application URL to wrap'
        required: true
        type: string
      version_name:
        description: 'Version name (e.g., 1.0.0)'
        required: true
        type: string
      version_code:
        description: 'Version code (integer)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build Success Notification
      run: |
        echo "🎉 Build completed successfully!"
        echo "App: ${{ github.event.inputs.app_name }}"
        echo "Package: ${{ github.event.inputs.package_id }}"
        echo "URL: ${{ github.event.inputs.web_app_url }}"
        echo "Version: ${{ github.event.inputs.version_name }} (${{ github.event.inputs.version_code }})"
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-app-${{ github.event.inputs.version_name }}
        path: |
          README.md
          .github/workflows/build-android-with-playstore.yml
